version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres 
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=ejercicio@correo.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pg:/var/lib/pgadmin

volumes:
  db:
    driver: local
  pg:
    driver: local